### ISSUE TITLE
Audio skipping issues

### ISSUE THREAD

**Issue by simonrodrig** [raudio-project/raudio-server#9]
Currently when interacting with the discord bot, sometimes the songs exhibit strange skipping or sped up behavior. I'm not sure if this is to do with the server, the bot, or simply discord, so more investigation will be required.

**Comment by itspaulyg** [comment]
@tfaughnan and I investigated this a bit earlier and determined that it seems to be a discord/bot issue. We came to this conclusion by testing on a secondary client, a safari browser, which did not skip or speed up the audio.

**Comment by simonrodrig** [comment]
@itspaulyg, okay cool, i will reopen on the bot repo
